version = 0.1
[default.deploy.parameters]
stack_name = "auto-account-creaton"
resolve_s3 = true
s3_prefix = "auto-account-creaton"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
