AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CheckAccountBullingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: check-account-bulling.lambda_handler
      Runtime: python3.12
      CodeUri: ./check-account-bulling/
      Policies:
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess
