AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CheckAccountBullingFunction:
    Type: AWS::Serverless::Function
    Metadata:
     BuildMethod: go1.x
    Properties:
      FunctionName: BudgetChecker
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./check-account-bulling/
      Policies:
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: "SNSTopic"

  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Metadata:
     BuildMethod: go1.x
    Properties:
      FunctionName: AccountCreator
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./create-account/
      Policies:
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: "SNSTopic"

  AddAccountInformationRecordFunction:
    Type: AWS::Serverless::Function
    Metadata:
     BuildMethod: go1.x
    Properties:
      FunctionName: AccountInformationRecorder
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./add-acount-information-record/
      Policies:
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: "SNSTopic"

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: BudgetNotificationTopic

