AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CheckAccountBullingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./check-account-bulling/
      Policies:
        - AWS::IAM::ManagedPolicy::AWSOrganizationsReadOnlyAccess
        - AWS::IAM::ManagedPolicy::AWSBudgetsServiceRolePolicyForResourceBased
        - AWS::IAM::ManagedPolicy::AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic
          
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: BudgetNotificationTopic

Outputs:
  BudgetCheckerFunctionArn:
    Description: "ARN of the Budget Checker Lambda Function"
    Value: !GetAtt BudgetCheckerFunction.Arn
  SNSTopicArn:
    Description: "SNS Topic ARN for Budget Notifications"
    Value: !Ref SNSTopic
