name: CI/CD Pipeline for AWS Lambda

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行
    paths:
      - 'script/**'  # scriptディレクトリ以下のファイルが変更されたときのみ実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのコードをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v2

      # AWS CLIのセットアップ
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # SAM CLIのセットアップ
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      # SAMビルド（scriptディレクトリを指定）
      - name: Build Lambda function
        run: |
          sam build --template-file script/template.yaml

      # SAMデプロイ（scriptディレクトリにあるsamconfig.tomlを使う）
      - name: Deploy Lambda function
        run: |
          sam deploy --config-file script/samconfig.toml
