name: CI/CD Pipeline for AWS Lambda

on:
  push:
    branches:
      - GoVersion  # GoVersionブランチにプッシュされたときに実行
    paths:
      - 'script/**'  # scriptディレクトリ以下のファイルが変更されたときのみ実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのコードをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Goをセットアップ
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'  # 必要に応じてGoのバージョンを変更

      # 3. Goコードのビルド (Linux用にクロスコンパイル)
      - name: Build Go for Linux
        run: |
          scripts/check-account-bulling
          GOOS=linux GOARCH=amd64 go build -o check-account-bulling check-account-bulling.go

      # AWS CLIのセットアップ
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # SAM CLIのセットアップ
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      # SAMビルド（scriptディレクトリを指定）
      - name: Build Lambda function
        run: |
          sam build --template-file script/template.yaml

      # SAMデプロイ（scriptディレクトリにあるsamconfig.tomlを使う）
      - name: Deploy Lambda function
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file script/samconfig.toml
